require('plugins_setup.autopairs')
require('plugins_setup.completion')
require('plugins_setup.autopairs')
require('plugins_setup.lsp')
require('plugins_setup.lualine_config')
require('plugins_setup.plug-colorizer')
require('plugins_setup.tree')
require('plugins_setup.treesitter')
require('plugins_setup.comment')
require('plugins_setup.nvim-ts-context-commentary')
require('plugins_setup.telescope-config')

require('remap')

require('plugins')
